use_frameworks!
#source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

AlivcSDK='AliVCSDK_InteractiveLive'
def common
  
  pod "#{AlivcSDK}", '~> 6.7.0'

  pod 'AUIFoundation/All', :path => '../AUIBaseKits/AUIFoundation/'
  pod 'AUIMessage/AliVCIM', :path => '../AUIBaseKits/AUIMessage/'
  
end

target 'AUICall1V1Example' do
  
  common
  pod "AUICall/RoomEngine_Lib/#{AlivcSDK}", :path => '../'
  pod 'AUICall/1V1', :path => '../'
  
end

target 'AUICallNVNExample' do
  
  common
  pod "AUICall/RoomEngine_Lib/#{AlivcSDK}", :path => '../'
  pod 'AUICall/NVN', :path => '../'
  
end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
               end
          end
   end
end
